-- ************************************** "asu_ter_k_main_locomotive"

CREATE TABLE "asu_ter_k_main_locomotive"
(
    "id"                            bigint                              NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "active"                        boolean                             NOT NULL,
    "change_time"                   timestamp default CURRENT_TIMESTAMP NOT NULL,
    "name"                          varchar(50)                         NOT NULL,
    "current"                       varchar(50)                         NOT NULL,
    "type"                          varchar(50)                         NOT NULL,
    "power"                         double precision                    NULL,
    "weight"                        double precision                    NOT NULL,
    "length"                        double precision                    NOT NULL,
    "max_speed"                     integer                             NOT NULL,
    "motor_type"                    varchar(50)                         NULL,
    "power_self_consumption"        double precision                    NULL,
    "amperage_self_consumption"     double precision                    NULL,
    "motor_thermal_characteristics" jsonb                               NULL,
    "resistance_to_motion"          jsonb                               NOT NULL,
    "electrical_characteristics"    jsonb                               NOT NULL,
    "braking_characteristics"       jsonb                               NULL,
    CONSTRAINT "PK_locomotive" PRIMARY KEY ("id")
);


-- ************************************** "asu_ter_k_main_car"

CREATE TABLE "asu_ter_k_main_car"
(
    "id"                   bigint                              NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "active"               boolean                             NOT NULL,
    "change_time"          timestamp default CURRENT_TIMESTAMP NOT NULL,
    "name"                 varchar(50)                         NOT NULL,
    "number_of_axles"      varchar(50)                         NOT NULL,
    "weight"               double precision                    NOT NULL,
    "length"               double precision                    NOT NULL,
    "resistance_to_motion" jsonb                               NOT NULL,
    CONSTRAINT "PK_car" PRIMARY KEY ("id")
);


-- ************************************** "asu_ter_k_main_train"

CREATE TABLE "asu_ter_k_main_train"
(
    "id"                       bigint      NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "active"                   boolean     NOT NULL,
    "change_time"              timestamp   NOT NULL,
    "name"                     varchar(50) NOT NULL,
    "brake_block_type"         varchar(50) NOT NULL,
    "brake_force"              double precision,
    "undercar_generator_power" double precision,
    "weight"                   double precision,
    "length"                   double precision,
    "resistance_to_motion"     jsonb,
    CONSTRAINT "PK_train" PRIMARY KEY ("id")
);


-- ************************************** "asu_ter_k_main_cars_to_train"

CREATE TABLE "asu_ter_k_main_cars_to_train"
(
    "train_id" bigint NOT NULL,
    "car_id"   bigint NOT NULL,
    "count"    int    NOT NULL,
    CONSTRAINT "PK_cars to train" PRIMARY KEY ("train_id", "car_id"),
    CONSTRAINT "FK_cars_to_train_to_train" FOREIGN KEY ("train_id") REFERENCES "asu_ter_k_main_train" ("id"),
    CONSTRAINT "FK_cars_to_train_to_car" FOREIGN KEY ("car_id") REFERENCES "asu_ter_k_main_car" ("id")
);

CREATE INDEX "fkIdx_cars_to_train_to_train" ON "asu_ter_k_main_cars_to_train"
    (
     "train_id"
        );

CREATE INDEX "fkIdx_cars_to_train_to_car" ON "asu_ter_k_main_cars_to_train"
    (
     "car_id"
        );


-- ************************************** "asu_ter_k_main_track"

CREATE TABLE "asu_ter_k_main_track"
(
    "id"               bigint       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "change_time"      timestamp    NOT NULL,
    "active"           boolean      NOT NULL,
    "name"             varchar(100) NOT NULL,
    "road"             varchar(50)  NOT NULL,
    "description"      varchar(200) NOT NULL,
    "number_of_tracks" int          NOT NULL,
    "different_tracks" boolean      NOT NULL,
    CONSTRAINT "PK_asu_ter_k_main_track" PRIMARY KEY ("id")
);


-- ************************************** "asu_ter_k_main_single_track"

CREATE TABLE "asu_ter_k_main_single_track"
(
    "id"           bigint      NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "track_id"     bigint      NOT NULL,
    "track_number" int         NOT NULL,
    "type"         varchar(50) NOT NULL,
    "elements"     jsonb       NOT NULL,
    CONSTRAINT "PK_asu_ter_k_main_single_track" PRIMARY KEY ("id"),
    CONSTRAINT "FK_single_track_to_track" FOREIGN KEY ("track_id") REFERENCES "asu_ter_k_main_track" ("id")
);

CREATE INDEX "fkIdx_single_track_to_track" ON "asu_ter_k_main_single_track"
    (
     "track_id"
        );


-- ************************************** "asu_ter_k_main_station"

CREATE TABLE "asu_ter_k_main_station"
(
    "id"              bigint           NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name"            varchar(100)     NOT NULL,
    "coordinate"      double precision NOT NULL,
    "loop_station"    boolean          NOT NULL,
    "single_track_id" bigint           NOT NULL,
    CONSTRAINT "PK_asu_ter_k_main_stations" PRIMARY KEY ("id"),
    CONSTRAINT "FK_station_to_single_track" FOREIGN KEY ("single_track_id") REFERENCES "asu_ter_k_main_single_track" ("id")
);

CREATE INDEX "fkIdx_station_to_single_track" ON "asu_ter_k_main_station"
    (
     "single_track_id"
        );


-- ************************************** "asu_ter_k_main_track_category"

CREATE TABLE "asu_ter_k_main_track_category"
(
    "id"              bigint      NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "single_track_id" bigint      NOT NULL,
    "name"            varchar(50) NOT NULL,
    "speed_limits"    jsonb       NOT NULL,
    "priority"        int         NOT NULL,
    CONSTRAINT "PK_asu_ter_k_main_track_category" PRIMARY KEY ("id"),
    CONSTRAINT "FK_track_category_to_single_track" FOREIGN KEY ("single_track_id") REFERENCES "asu_ter_k_main_single_track" ("id")
);

CREATE INDEX "fkIdx_track_category_to_single_track" ON "asu_ter_k_main_track_category"
    (
     "single_track_id"
        );


-- ************************************** "asu_ter_k_main_tractive_calculate"

CREATE TABLE "asu_ter_k_main_tractive_calculate"
(
    "id"               bigint       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "track_id"         bigint       NOT NULL,
    "direction"        boolean      NOT NULL,
    "category_id"      bigint       NOT NULL,
    "locomotive_id"    bigint       NOT NULL,
    "train_id"         bigint       NOT NULL,
    "active"           boolean      NOT NULL,
    "change_time"      timestamp    NOT NULL,
    "description"      varchar(200) NOT NULL,
    "weight"           int          NOT NULL,
    "result"           jsonb        NOT NULL,
    "stop_coordinates" jsonb        NOT NULL,
    "single_track_id"  bigint       NOT NULL,
    CONSTRAINT "PK_asu_ter_k_main_tractive_calculate" PRIMARY KEY ("id"),
    CONSTRAINT "FK_tractive_calculate_to_category" FOREIGN KEY ("category_id") REFERENCES "asu_ter_k_main_track_category" ("id"),
    CONSTRAINT "FK_tractive_calculate_to_locomotive" FOREIGN KEY ("locomotive_id") REFERENCES "asu_ter_k_main_locomotive" ("id"),
    CONSTRAINT "FK_tractive_calculate_to_single_track" FOREIGN KEY ("single_track_id") REFERENCES "asu_ter_k_main_single_track" ("id"),
    CONSTRAINT "FK_tractive_calculate_to_track" FOREIGN KEY ("track_id") REFERENCES "asu_ter_k_main_track" ("id"),
    CONSTRAINT "FK_tractive_calculate_to_train" FOREIGN KEY ("train_id") REFERENCES "asu_ter_k_main_train" ("id")
);

CREATE INDEX "fkIdx_tractive_calculate_to_category" ON "asu_ter_k_main_tractive_calculate"
    (
     "category_id"
        );

CREATE INDEX "fkIdx_tractive_calculate_to_locomotive" ON "asu_ter_k_main_tractive_calculate"
    (
     "locomotive_id"
        );

CREATE INDEX "fkIdx_tractive_calculate_to_single_track" ON "asu_ter_k_main_tractive_calculate"
    (
     "single_track_id"
        );

CREATE INDEX "fkIdx_tractive_calculate_to_track" ON "asu_ter_k_main_tractive_calculate"
    (
     "track_id"
        );

CREATE INDEX "fkIdx_tractive_calculate_to_train" ON "asu_ter_k_main_tractive_calculate"
    (
     "train_id"
        );


-- ************************************** "asu_ter_k_main_schedule"

CREATE TABLE "asu_ter_k_main_schedule"
(
    "id"          bigint       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name"        varchar(200) NOT NULL,
    "active"      boolean      NOT NULL,
    "change_time" timestamp    NOT NULL,
    "intervals"   jsonb        NOT NULL,
    CONSTRAINT "PK_asu_ter_k_main_schedules" PRIMARY KEY ("id")
);


-- ************************************** "asu_ter_k_main_train_slot"

CREATE TABLE "asu_ter_k_main_train_slot"
(
    "id"                    bigint           NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "tractive_calculate_id" bigint           NOT NULL,
    "schedule_id"           bigint           NOT NULL,
    "periods"               jsonb            NOT NULL,
    "start_time"            double precision NOT NULL,
    "finish_time"           double precision NOT NULL,
    CONSTRAINT "PK_asu_ter_k_main_train_slot" PRIMARY KEY ("id"),
    CONSTRAINT "FK_train_slot_to_tractive_calculate" FOREIGN KEY ("tractive_calculate_id") REFERENCES "asu_ter_k_main_tractive_calculate" ("id"),
    CONSTRAINT "FK_train_slot_to_schedule" FOREIGN KEY ("schedule_id") REFERENCES "asu_ter_k_main_schedule" ("id")
);

CREATE INDEX "fkIdx_train_slot_to_tractive_calculate" ON "asu_ter_k_main_train_slot"
    (
     "tractive_calculate_id"
        );

CREATE INDEX "fkIdx_train_slot_to_schedule" ON "asu_ter_k_main_train_slot"
    (
     "schedule_id"
        );



-- ************************************** "тяговые сети"


-- ************************************** "asu_ter_m_transformer"

CREATE TABLE "asu_ter_m_transformer"
(
    "id"                       bigint           NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "active"                   boolean          NOT NULL,
    "change_time"              timestamp        NOT NULL,
    "name"                     varchar(50)      NOT NULL,
    "type"                     varchar(50),
    "power"                    int              NOT NULL,
    "voltage"                  double precision NOT NULL,
    "schema"                   varchar(50),
    "voltage_regulation"       double precision,
    "voltage_short_circuit"    double precision NOT NULL,
    "power_loss_short_circuit" double precision NOT NULL,
    "power_loss_no_load"       double precision NOT NULL,
    "amperage_no_load"         double precision NOT NULL,
    CONSTRAINT "PK_asu_ter_m_transformer" PRIMARY KEY ("id")
);


-- ************************************** "asu_ter_m_wire_and_rail"

CREATE TABLE "asu_ter_m_wire_and_rail"
(
    "id"                   bigint           NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "active"               boolean          NOT NULL,
    "change_time"          timestamp        NOT NULL,
    "name"                 varchar(50)      NOT NULL,
    "direct_resistance"    double precision NOT NULL,
    "alternate_resistance" double precision NOT NULL,
    "radius"               double precision NOT NULL,
    "limit_amperage"       double precision NULL,
    "limit_temperature"    int              NULL,
    "thermal_constant"     double precision NULL,
    CONSTRAINT "PK_asu_ter_m_wire_and_rail" PRIMARY KEY ("id")
);


-- ************************************** "asu_ter_m_compensation_device_upk"

CREATE TABLE "asu_ter_m_compensation_device_upk"
(
    "id"                  bigint           NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "active"              boolean          NOT NULL,
    "change_time"         timestamp        NOT NULL,
    "name"                varchar(50)      NOT NULL,
    "regulation_type"     varchar(50)      NOT NULL,
    "regulation_diapason" double precision NULL,
    "nominal_power"       double precision NOT NULL,
    "nominal_amperage"    double precision NOT NULL,
    "resistance"          double precision NOT NULL,
    CONSTRAINT "PK_asu_ter_m_compensation_device_upk" PRIMARY KEY ("id")
);


-- ************************************** "asu_ter_m_compensation_device_uk"

CREATE TABLE "asu_ter_m_compensation_device_uk"
(
    "id"                  bigint           NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "active"              boolean          NOT NULL,
    "change_time"         timestamp        NOT NULL,
    "name"                varchar(50)      NOT NULL,
    "regulation_type"     varchar(50)      NOT NULL,
    "regulation_diapason" double precision NULL,
    "nominal_power"       double precision NOT NULL,
    "useful_power"        double precision NOT NULL,
    "resistance"          double precision NOT NULL,
    CONSTRAINT "PK_asu_ter_m_compensation_device_uk" PRIMARY KEY ("id")
);


-- ************************************** "asu_ter_m_direct_network"

CREATE TABLE "asu_ter_m_direct_network"
(
    "id"                 bigint           NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name"               varchar(100)     NOT NULL,
    "fider_id"           bigint           NOT NULL,
    "fider_count"        int              NOT NULL,
    "contact_wire_id"    bigint           NULL,
    "contact_wire_count" int              NULL,
    "power_wire_id"      bigint           NULL,
    "power_wire_count"   int              NULL,
    "rail_id"            bigint           NULL,
    "rail_count"         int              NULL,
    "wires_resistance"   double precision NOT NULL,
    "rails_resistance"   double precision NULL,
    "limit_amperage"     double precision NOT NULL,
    "limit_temperature"  int              NOT NULL,
    "thermal_constant"   double precision NOT NULL,
    "contact_amperage"   double precision NULL,
    CONSTRAINT "PK_asu_ter_m_direct_network" PRIMARY KEY ("id"),
    CONSTRAINT "FK_asu_ter_m_direct_network_contact_wire" FOREIGN KEY ("contact_wire_id") REFERENCES "asu_ter_m_wire_and_rail" ("id"),
    CONSTRAINT "FK_asu_ter_m_direct_network_fider" FOREIGN KEY ("fider_id") REFERENCES "asu_ter_m_wire_and_rail" ("id"),
    CONSTRAINT "FK_asu_ter_m_direct_network_power_wire" FOREIGN KEY ("power_wire_id") REFERENCES "asu_ter_m_wire_and_rail" ("id"),
    CONSTRAINT "FK_asu_ter_m_direct_network_rail" FOREIGN KEY ("rail_id") REFERENCES "asu_ter_m_wire_and_rail" ("id")
);

CREATE INDEX "fkIdx_asu_ter_m_direct_network_contact_wire" ON "asu_ter_m_direct_network"
    (
     "contact_wire_id"
        );

CREATE INDEX "fkIdx_asu_ter_m_direct_network_fider" ON "asu_ter_m_direct_network"
    (
     "fider_id"
        );

CREATE INDEX "fkIdx_asu_ter_m_direct_network_power_wire" ON "asu_ter_m_direct_network"
    (
     "power_wire_id"
        );

CREATE INDEX "fkIdx_asu_ter_m_direct_network_rail" ON "asu_ter_m_direct_network"
    (
     "rail_id"
        );


-- ************************************** "asu_ter_m_alternate_network"

CREATE TABLE "asu_ter_m_alternate_network"
(
    "id"               bigint           NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "description"      varchar(100)     NOT NULL,
    "track_count"      int              NOT NULL,
    "earth_resistance" double precision NOT NULL,
    "parameters"       jsonb            NOT NULL,
    CONSTRAINT "PK_asu_ter_m_alternate_network" PRIMARY KEY ("id")
);


-- ************************************** "asu_ter_m_alternate_network_to_wires"

CREATE TABLE "asu_ter_m_alternate_network_to_wires"
(
    "id"                  bigint           NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "wire_id"             bigint           NOT NULL,
    "network_id"          bigint           NOT NULL,
    "type"                varchar(50)      NOT NULL,
    "track_number"        int              NOT NULL,
    "height_position"     double precision NOT NULL,
    "horizontal_position" double precision NOT NULL,
    CONSTRAINT "PK_asu_ter_m_alternate_network_to_wires" PRIMARY KEY ("id"),
    CONSTRAINT "FK_network_alternate_network_to_wires" FOREIGN KEY ("network_id") REFERENCES "asu_ter_m_alternate_network" ("id"),
    CONSTRAINT "FK_wire_alternate_network_to_wires" FOREIGN KEY ("wire_id") REFERENCES "asu_ter_m_wire_and_rail" ("id")
);

CREATE INDEX "fkIdx_network_alternate_network_to_wires" ON "asu_ter_m_alternate_network_to_wires"
    (
     "network_id"
        );

CREATE INDEX "fkIdx_wire_alternate_network_to_wires" ON "asu_ter_m_alternate_network_to_wires"
    (
     "wire_id"
        );

